
plugins = [
  "pycodestyle",
  "pydocstyle",
  "pylint",
  "rope_completion",
  "jedi_completion",
  "jedi_hover"
]

[tool.pylsp.plugins.pylint]
enabled = true

[tool.pylsp.plugins.pycodestyle]
enabled = true
maxLineLength = 120
ignore = ["E501"]

[tool.pylsp.plugins.pydocstyle]
enabled = false

[tool.pylsp.plugins.rope_completion]
enabled = true

[tool.pylsp.plugins.jedi_completion]
enabled = true

[tool.pylsp.plugins.jedi_hover]
enabled = true
