# 数据存储与管理配置
# 示例内容，可根据实际需求补充
paths:
  data_root: ./data
  raw: ./data/raw
  processed: ./data/processed
  sectors: ./data/sectors
  industries: ./data/industries
  indices: ./data/indices
  calendar: ./data/calendar
  metadata: ./data/metadata
frequencies: [daily, weekly, monthly, 30min, 60min, 120min]
data_sources:
  - name: local_csv
    type: csv
    path: ./data/raw
  # 可扩展更多数据源
